import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="container mx-auto px-4">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
